//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShivaQEmaster.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public language_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShivaQEmaster.Languages.language_en-US", typeof(language_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addserverpage_bt_add {
            get {
                return ResourceManager.GetString("addserverpage_bt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD COMPUTER FROM NETWORK.
        /// </summary>
        public static string addserverpage_header {
            get {
                return ResourceManager.GetString("addserverpage_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosname (or IP) :.
        /// </summary>
        public static string addserverpage_lb_host {
            get {
                return ResourceManager.GetString("addserverpage_lb_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name (optional) :.
        /// </summary>
        public static string addserverpage_lb_name {
            get {
                return ResourceManager.GetString("addserverpage_lb_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mypc.net or 10.42.4.2.
        /// </summary>
        public static string addserverpage_tb_host {
            get {
                return ResourceManager.GetString("addserverpage_tb_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mypc.
        /// </summary>
        public static string addserverpage_tb_name {
            get {
                return ResourceManager.GetString("addserverpage_tb_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Recording.
        /// </summary>
        public static string flyout_ts_record_off {
            get {
                return ResourceManager.GetString("flyout_ts_record_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string flyout_ts_record_on {
            get {
                return ResourceManager.GetString("flyout_ts_record_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string global_bt_close {
            get {
                return ResourceManager.GetString("global_bt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string helppage_header {
            get {
                return ResourceManager.GetString("helppage_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://zougi.github.io/ShivaQE.
        /// </summary>
        public static string helppage_hl_website {
            get {
                return ResourceManager.GetString("helppage_hl_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2014.
        /// </summary>
        public static string helppage_tb_copyright {
            get {
                return ResourceManager.GetString("helppage_tb_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zougi.github.io/ShivaQE.
        /// </summary>
        public static string helppage_tb_website {
            get {
                return ResourceManager.GetString("helppage_tb_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string homepage_bt_add {
            get {
                return ResourceManager.GetString("homepage_bt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string homepage_bt_disconnect {
            get {
                return ResourceManager.GetString("homepage_bt_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string homepage_bt_reconnect {
            get {
                return ResourceManager.GetString("homepage_bt_reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string homepage_bt_record {
            get {
                return ResourceManager.GetString("homepage_bt_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string homepage_bt_remove {
            get {
                return ResourceManager.GetString("homepage_bt_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string homepage_gd_header_ip {
            get {
                return ResourceManager.GetString("homepage_gd_header_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string homepage_gd_header_name {
            get {
                return ResourceManager.GetString("homepage_gd_header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string homepage_gd_header_status {
            get {
                return ResourceManager.GetString("homepage_gd_header_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop sending.
        /// </summary>
        public static string homepage_ts_broadcast_off {
            get {
                return ResourceManager.GetString("homepage_ts_broadcast_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mouse/keys.
        /// </summary>
        public static string homepage_ts_broadcast_on {
            get {
                return ResourceManager.GetString("homepage_ts_broadcast_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable trace log.
        /// </summary>
        public static string settingspage_cb_trace {
            get {
                return ResourceManager.GetString("settingspage_cb_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate anonymous reporting to help enhance ShivaQE.
        /// </summary>
        public static string settingspage_cb_tracking {
            get {
                return ResourceManager.GetString("settingspage_cb_tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string settingspage_lb_general {
            get {
                return ResourceManager.GetString("settingspage_lb_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mouse/keys Off.
        /// </summary>
        public static string settingspage_lb_key_broadcast_off {
            get {
                return ResourceManager.GetString("settingspage_lb_key_broadcast_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mouse/keys On.
        /// </summary>
        public static string settingspage_lb_key_broadcast_on {
            get {
                return ResourceManager.GetString("settingspage_lb_key_broadcast_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide window.
        /// </summary>
        public static string settingspage_lb_key_hide_window {
            get {
                return ResourceManager.GetString("settingspage_lb_key_hide_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string settingspage_lb_shortcuts {
            get {
                return ResourceManager.GetString("settingspage_lb_shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        public static string settingspage_wm_key {
            get {
                return ResourceManager.GetString("settingspage_wm_key", resourceCulture);
            }
        }
    }
}
