//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShivaQEviewer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public language_en_US()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShivaQEviewer.Languages.language_en-US", typeof(language_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SERVER.
        /// </summary>
        public static string addserverpage_header {
            get {
                return ResourceManager.GetString("addserverpage_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosname (or IP) :.
        /// </summary>
        public static string addserverpage_lb_host {
            get {
                return ResourceManager.GetString("addserverpage_lb_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name (optional) :.
        /// </summary>
        public static string addserverpage_lb_name {
            get {
                return ResourceManager.GetString("addserverpage_lb_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Login :.
        /// </summary>
        public static string addserverpage_lb_win_login {
            get {
                return ResourceManager.GetString("addserverpage_lb_win_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Password :.
        /// </summary>
        public static string addserverpage_lb_win_password {
            get {
                return ResourceManager.GetString("addserverpage_lb_win_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mypc.net or 10.42.4.2.
        /// </summary>
        public static string addserverpage_tb_host {
            get {
                return ResourceManager.GetString("addserverpage_tb_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mypc.
        /// </summary>
        public static string addserverpage_tb_name {
            get {
                return ResourceManager.GetString("addserverpage_tb_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domain\login.
        /// </summary>
        public static string addserverpage_tb_win_login {
            get {
                return ResourceManager.GetString("addserverpage_tb_win_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string global_bt_close {
            get {
                return ResourceManager.GetString("global_bt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string helppage_header {
            get {
                return ResourceManager.GetString("helppage_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string homepage_bt_add {
            get {
                return ResourceManager.GetString("homepage_bt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string homepage_bt_remove {
            get {
                return ResourceManager.GetString("homepage_bt_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string homepage_bt_view {
            get {
                return ResourceManager.GetString("homepage_bt_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string homepage_gd_header_ip {
            get {
                return ResourceManager.GetString("homepage_gd_header_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string homepage_gd_header_login {
            get {
                return ResourceManager.GetString("homepage_gd_header_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string homepage_gd_header_name {
            get {
                return ResourceManager.GetString("homepage_gd_header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string resolutionpage_bt_ok {
            get {
                return ResourceManager.GetString("resolutionpage_bt_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOLUTION.
        /// </summary>
        public static string resolutionpage_header {
            get {
                return ResourceManager.GetString("resolutionpage_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height :.
        /// </summary>
        public static string resolutionpage_lb_height {
            get {
                return ResourceManager.GetString("resolutionpage_lb_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        public static string resolutionpage_lb_px {
            get {
                return ResourceManager.GetString("resolutionpage_lb_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width :.
        /// </summary>
        public static string resolutionpage_lb_width {
            get {
                return ResourceManager.GetString("resolutionpage_lb_width", resourceCulture);
            }
        }
    }
}
